<?php  global $REPORTSDB, $ERR_MSG;  ?>

 <script type="text/javascript" src="template/js/misc.js"></script>
 <script type="text/javascript" src="template/js/jquery.js"></script>
 <script type="text/javascript">
        // Links for jquery.js, used for animated show/hide links.
        // Some of these need to be autogenerated with PHP, so were putting this directly
        // in the template.
        $(document).ready(function() {
                $('#myreports-toggle').click(function() {$('#myreports').slideToggle(900);return false;});
                $('#unfinished-toggle').click(function() {$('#unfinished').slideToggle('slow');return false;});
                $('#newreports-toggle').click(function() {$('#newreports').slideToggle(900);return false;});
        });
 </script>


<table width="100%" cellpadding="0" cellspacing="0" align="center">
  <tr>
    <td style="height: 5px;"> </td>
  </tr>
  <tr>
    <td valign="top">

      <?php  include('left_navbar.inc.php');  ?>

    </td>
    <td valign="top">

      <!-- Center Column -->
      <div class="center_column">

        <?php
          if ( !empty($ERR_MSG) )  {
        ?>
        <table width="100%" align="center">
          <tr>
            <td align="center">
              <div class="error">
                <?php  print $ERR_MSG . "\n";  ?>
              </div>
            </td>
          </tr>
        </table>
        <br /><br />
        <?php  }  ?>

        <table align="center" cellpadding="0" cellspacing="0" width="100%" style="overflow:hidden;">
          <tr>
            <td valign="top" class="module_body_outer">


              <!-- My Reports -->
              <div class="module_body_outer">
                <div class="module_header">
                  <div class="row">
                    <span class="left">
                      <abbr title="<?php print HELP_HOME_MY_REPORTS; ?>">
                        <strong> <?php print HOME_MY_REPORTS; ?> </strong>
                      </abbr>
                    </span>
                    <span class="right">
                      <a href="#" id="myreports-toggle"><img src="images/openclose.gif" border="0"></a>
                    </span>
                    <div style="clear:both;"> </div>
                  </div>
                </div>

                <div class="module_body_inner" id="myreports" style="display:block;">
                  <div class="module_prop"> </div>

                  <?php
			global $HOME_LIST_LIMIT;
			print_reports( $_SESSION['user_id'], $HOME_LIST_LIMIT );
                  ?>

                  <div class="clear"> </div>
                </div>
              </div>
            <!-- My Reports -->


            </td>
            <td style="width:3px">&nbsp;</td>
            <td valign="top" class="module_body_outer">


              <!-- Unfinished Reports -->
              <div class="module_body_outer">
                <div class="module_header">
                  <div class="row">
                    <span class="left">
                      <abbr title="<?php print HELP_HOME_UNFINISHED_REPORTS; ?>">
                        <strong> <?php print HOME_UNFINISHED_REPORTS; ?> </strong>
                      </abbr>
                    </span>
                    <span class="right">
                      <a href="#" id="unfinished-toggle"><img src="images/openclose.gif" border="0"></a>
                    </span>
                    <div style="clear:both;"> </div>
                  </div>
                </div>

                <div class="module_body_inner" id="unfinished" style="display:block;">
                  <div class="module_prop"> </div>

                  <?php
			print_unfinished_reports( $_SESSION['user_id'] );
                  ?>

                  <div class="clear"> </div>
                </div>
              </div>
              <!-- Unfinished Reports -->


            </td>
            <td style="width:3px">&nbsp;</td>
            <td valign="top" class="module_body_outer">


              <!-- Recently Published -->
              <div class="module_body_outer">
                <div class="module_header">
                  <div class="row">
                    <span class="left">
                      <abbr title="<?php print HELP_HOME_RECENTLY_EDITED_REPORTS; ?>">
                        <strong> <?php print HOME_RECENTLY_EDITED_REPORTS; ?> </strong>
                      </abbr>
                      <a href="<?php print $REPORTSDB; ?>?task=print_rss"><img src="images/feed-icon.png" border="0"></a>
                    </span>
                    <span class="right">
                      <a href="#" id="newreports-toggle"><img src="images/openclose.gif" border="0"></a>
                    </span>
                    <div style="clear:both;"> </div>
                  </div>
                </div>

                <div class="module_body_inner" id="newreports" style="display:block;">
                  <div class="module_prop"> </div>

                  <?php
			print_newest_reports();
                  ?>

                  <div class="clear"> </div>
                </div>
              </div>
              <!-- Recently Published -->

            </td>
          </tr>
          <tr>
            <td colspan="3">
              <br /><br />
              <strong> Note: </strong> Please do not publish walkthrough reports until after the investigation. <br />
              All reports will be published automatically when the associated case expires.
            </td>
          <tr>
        </table>

      </div>
      <!-- Center Column -->


    </tr>
  </td>
</table>


