<?php
	global $REPORTS_VALID_FIELDS, $REPORTS_IMPRESSIONS_VALID_FIELDS, $REPORTS_ROOM_DATA_VALID_FIELDS, $NUM_ROOMS;
	global $REPORTSDB, $USER_PERMS, $ERR_MSG, $TITLE, $TECH_UNITS;
	global $LOGIN_DB_ID_COL, $LOGIN_DB_USER_COL, $LOGIN_DB_NAME_COL;
	for ( $i=1; $i<$NUM_ROOMS+1; $i++ )  {
		global ${'ROOM_DATA_'.$i};
	}
?>

 <script type="text/javascript" src="template/js/tabber-minimized.js"></script>
 <script type="text/javascript" src="template/js/misc.js"></script>
 <script type="text/javascript" src="template/js/report.js"></script>
 <script type="text/javascript" src="template/js/anomaly.js"></script>
 <script type="text/javascript" src="template/js/jquery.js"></script>

 <script type="text/javascript">
	// Links for jquery.js, used for animated show/hide links.
	// Some of these need to be autogenerated with PHP, so were putting this directly
	// in the template.
	$(document).ready(function() {
		$('#equip_fields-toggle').click(function() {$('#equip_fields').slideToggle(450);return false;});
		$('#impressions_fields-toggle').click(function() {$('#impressions_fields').slideToggle(450);return false;});
		<?php
			for ( $i=0; $i<$NUM_ROOMS+1; $i++ )  {
				print '$(\'#room_fields_' . $i . '-toggle\').click(function() {$(\'#room_fields_' . $i . '\').slideToggle(450);return false;});' . "\n";
				print '$(\'#advanced_reporting_fields_' . $i . '-toggle\').click(function() {$(\'#advanced_reporting_fields_' . $i . '\').slideToggle(450);return false;});' . "\n";
				print '$(\'#notes_field_' . $i . '-toggle\').click(function() {$(\'#notes_field_' . $i . '\').slideToggle(450);return false;});' . "\n";
			}
		?>
	});
 </script>


 <link rel="stylesheet" href="template/tabs.css" type="text/css">

 <script type="text/javascript">
 // <!--
	var tech_index = 1;
	var audio_index = 1;
	var video_index = 1;
	var photo_index = 1;
	var psi_index = 1;

	<?php
		// Find out how may rooms are full.  Rooms are shifted up each time the form
		// is saved, so we can just stop as soon as we find an empty on.
		for ( $num_full=1; $num_full<$NUM_ROOMS+1; $num_full++ )  {
			if ( room_isempty($num_full) )  {
				break;
			}
		}
		if ( $num_full > 1 )  {
			print "var room_index = " . ($num_full-1) . ";\n";
		}
		else  {
			print "var room_index = " . $num_full . ";\n";
		}
	?>
 // -->
 </script>

<table width="100%" cellpadding="0" cellspacing="0" align="center">
  <tr>
    <td style="height:5px"> </td>
  </tr>
  <tr>
    <td valign="top" style="width:150px;">

      <?php  include('left_navbar.inc.php');  ?>

    </td>
    <td valign="top" style="padding:0px;margin:0;" width="100%">

      <!-- Center Column -->
      <div class="center_column">

        <?php
          if ( !empty($ERR_MSG) )  {
        ?>
        <div width="100%" align="center">
          <div class="error">
            <?php  print $ERR_MSG . "\n";  ?>
          </div>
        </div>
        <br /><br />
        <?php  }  ?>

        <?php
		if ( $_REQUEST['task'] == 'save_report' )  {
			print set_required_fields( $REPORTS_VALID_FIELDS );
			print set_required_room_fields();
		}
        ?>


        <!-- Report Form -->
        <form name="main" action="<?php print $REPORTSDB; ?>" method="post">
        <input type="hidden" name="task" value="save_report" />
        <input type="hidden" name="owner_id" value="<?php print $REPORTS_VALID_FIELDS['owner_id']['value']; ?>" />


        <!-- Report and Case Information -->
        <table cellspacing="0" cellpadding="0" align="center" class="form_table_main">
          <tr>
            <td colspan="3" style="height:10px;">

              <div class="medium" id="toplinks">
                <?php
			if ( report_exists($REPORTS_VALID_FIELDS['case_id']['value'], $REPORTS_VALID_FIELDS['owner_id']['value']) == 0 )  {
				print "<a href=\"" . $REPORTSDB . "?task=view_report&case_id=" . $REPORTS_VALID_FIELDS['case_id']['value'] . "&owner_id=" . $REPORTS_VALID_FIELDS['owner_id']['value'] . "\">" . TASK_VIEW_REPORT . "</a>\n";
				if ( report_check_perms('d', $REPORTS_VALID_FIELDS['case_id']['value'], $REPORTS_VALID_FIELDS['owner_id']['value']) == 0 )  {
					print " | <a href=\"" . $REPORTSDB . "?task=delete_report&case_id=" . $REPORTS_VALID_FIELDS['case_id']['value'] . "&owner_id=" . $REPORTS_VALID_FIELDS['owner_id']['value'] . "&confirm_delete=0\">" . TASK_DELETE_REPORT . "</a>\n";
				}
			}
                ?>
                &nbsp;
              </div>
            </td>
          </tr>
          <tr>
            <td colspan="3" style="height:8px !important;height:1px"> </td>
          </tr>
          <tr>
            <td width="55%" valign="top" style="padding:0px 10px 0px 5px;">

              <strong> <?php print REPORT_LABEL_REPORT_DETAILS; ?> </strong>
              <abbr title="<?php print HELP_REPORT_DETAILS; ?>"><img src="images/help.gif"></abbr>
              <table cellpadding="0" cellspacing="4" width="100%">
                <tr>
                  <td id="label1"> <?php print CASE_ID; ?> </td>
                  <td id="value1">

                    <select name="case_id" id="case_id" size="1">
                    <?php
			if ( !empty($REPORTS_VALID_FIELDS['case_id']['value']) )  {
				print "<option value=\"" . $REPORTS_VALID_FIELDS['case_id']['value'] . "\">" . $REPORTS_VALID_FIELDS['case_id']['value'] . "\n";
			}
			elseif ( $_REQUEST['case_id'] == 'new' || empty($_REQUEST['case_id']) )  {
				$valid_cases = list_unfinished_reports( $_SESSION['user_id'] );
				foreach ( array_keys($valid_cases) as $key )  {
					if ( !check_case_expired($key) )  {
						print "<option value=\"" . $key . "\">" . $key . "\n";
					}
				}
                    ?>
                    <?php  }  ?>
                    </select>

                    <?php
			if ( report_exists($REPORTS_VALID_FIELDS['case_id']['value'], $REPORTS_VALID_FIELDS['owner_id']['value']) == 0 )  {
				print "<a href=\"" . $REPORTSDB . "?task=view_case&case_id=" . $REPORTS_VALID_FIELDS['case_id']['value'] . "\" target=\"_blank\">" . TASK_VIEW_CASE . "</a>\n";
			}
                    ?>

                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print REPORT_REPORT_STATE; ?> </td>
                  <td id="value1">
                    <select name="report_state" id="report_state" size="1">
                      <?php
                        if ( $REPORTS_VALID_FIELDS['report_state']['value'] == "" || $REPORTS_VALID_FIELDS['report_state']['value'] == "unpublished" )  {
                      ?>
                      <option value="unpublished">Unpublished
                      <option value="published">Published
                      <?php
                        }
                        else  {
                      ?>
                      <option value="published">Published
                      <option value="unpublished">Unpublished
                      <?php  }  ?>
                    </select>
                    <abbr title="<?php print HELP_REPORT_STATE; ?>"><img src="images/help.gif"></abbr>
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print REPORT_TITLE; ?> </td>
                  <td id="value1">
                    <input type="text" name="case_title" id="case_title" size="40" style="width:75%;" value="<?php print $REPORTS_VALID_FIELDS['case_title']['value']; ?>" size="12" maxlength="<?php print $REPORTS_VALID_FIELDS['case_title']['maxlength']; ?>" />
                  </td>
                </tr>
                <tr>
                  <td id="label1" valign="top"> <?php print REPORT_DESCRIPTION; ?> </td>
                  <td id="value1">
                    <textarea name="description" id="description" rows="5" cols="35" style="width:95%;"><?php print $REPORTS_VALID_FIELDS['description']['value']; ?></textarea>
                    <div style="text-align:right;padding-right:20px;">
                      <a href="JavaScript:taller('description')" class="small"><?php print TEXTAREA_TALLER; ?></a> |
                      <a href="JavaScript:shorter('description')" class="small"><?php print TEXTAREA_SHORTER; ?></a>
                    </div>
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print REPORT_START_TIME; ?> </td>
                  <td id="value1">

                    <!-- start_time_hour -->
                    <select name="start_time_hour" id="start_time_hour" size="1">
                      <option>
                      <?php
			for ( $i=0; $i<24; $i++ )  {
				if ( $i < 10 )  {  $i = 0 . $i;  }
				print "<option value=\"" . $i . "\">" . $i . "\n";
			}
                      ?>
                    </select>
                    <?php
                        if ( !empty($REPORTS_VALID_FIELDS['start_time_hour']['value']) )  {
                    ?>
                    <script language="JavaScript">
                        // <!--
                        selectoption('start_time_hour',<?php print $REPORTS_VALID_FIELDS['start_time_hour']['value']; ?>);
                        // -->
                    </script>
                    <?php  }  ?>
                    <!-- start_time_hour -->

                    <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>

                    <!-- start_time_minute -->
                    <select name="start_time_minute" id="start_time_minute" size="1">
                      <option>
                      <?php
			for ( $i=0; $i<60; $i++ )  {
				if ( $i < 10 )  {  $i = 0 . $i;  }
				print "<option value=\"" . $i . "\">" . $i . "\n";
			}
                      ?>
                    </select>
                    <?php
                        if ( !empty($REPORTS_VALID_FIELDS['start_time_minute']['value']) )  {
                    ?>
                    <script language="JavaScript">
                        // <!--
                        selectoption('start_time_minute',<?php print $REPORTS_VALID_FIELDS['start_time_minute']['value']; ?>);
                        // -->
                    </script>
                    <?php  }  ?>
                    <!-- start_time_minute -->

                    <abbr title="<?php print HELP_REPORT_START_TIME; ?>"><img src="images/help.gif"></abbr>
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print REPORT_END_TIME; ?> </td>
                  <td id="value1">

                    <!-- end_time_hour -->
                    <select name="end_time_hour" id="end_time_hour" size="1">
                      <option>
                      <?php
			for ( $i=0; $i<24; $i++ )  {
				if ( $i < 10 )  {  $i = 0 . $i;  }
				print "<option value=\"" . $i . "\">" . $i . "\n";
			}
                      ?>
                    </select>
                    <?php
                        if ( !empty($REPORTS_VALID_FIELDS['end_time_hour']['value']) )  {
                    ?>
                    <script language="JavaScript">
                        // <!--
                        selectoption('end_time_hour',<?php print $REPORTS_VALID_FIELDS['end_time_hour']['value']; ?>);
                        // -->
                    </script>
                    <?php  }  ?>
                    <!-- end_time_hour -->

                    <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>

                    <!-- end_time_minute -->
                    <select name="end_time_minute" id="end_time_minute" size="1">
                      <option>
                      <?php
			for ( $i=0; $i<60; $i++ )  {
				if ( $i < 10 )  {  $i = 0 . $i;  }
				print "<option value=\"" . $i . "\">" . $i . "\n";
			}
                      ?>
                    </select>
                    <?php
                        if ( !empty($REPORTS_VALID_FIELDS['end_time_minute']['value']) )  {
                    ?>
                    <script language="JavaScript">
                        // <!--
                        selectoption('end_time_minute',<?php print $REPORTS_VALID_FIELDS['end_time_minute']['value']; ?>);
                        // -->
                    </script>
                    <?php  }  ?>
                    <!-- end_time_minute -->

                    <abbr title="<?php print HELP_REPORT_END_TIME; ?>"><img src="images/help.gif"></abbr>
                  </td>
                </tr>
              </table>

            </td>
            <td valign="top">

              <?php
		if ( report_exists($REPORTS_VALID_FIELDS['case_id']['value'], $REPORTS_VALID_FIELDS['owner_id']['value']) == 0 )  {
			$case_id = $REPORTS_VALID_FIELDS['case_id']['value'];
			$case_info = list_case_info( $case_id );
		}
		elseif ( isset($_REQUEST['case_id']) && !empty($_REQUEST['case_id']) )  {
			$case_id = $_REQUEST['case_id'];
			$case_info = list_case_info( $case_id );
		}
		else  {
			$case_id = 'new';
			$case_info[$case_id]['owner_id'] = "";
			$case_info[$case_id]['investigation_title'] = "";
			$case_info[$case_id]['date'] = "";
			$case_info[$case_id]['time'] = "";
			$case_info[$case_id]['expiration_date'] = "";
			$case_info[$case_id]['city'] = "";
			$case_info[$case_id]['state'] = "";
			$case_info[$case_id]['loc_type'] = "";
			$case_info[$case_id]['case_open'] = "";
			$case_info[$case_id]['investigation_type'] = "";
			$case_info[$case_id]['recap_date'] = "";
			$case_info[$case_id]['recap_time'] = "";
			$case_info[$case_id]['recap_location'] = "";
		}
              ?>
              <p><strong> <?php print CASE_LABEL_CASE_DETAILS; ?> </strong>
              <abbr title="<?php print HELP_CASE_DETAILS; ?>"><img src="images/help.gif"></abbr>
              <table cellpadding="0" cellspacing="4" width="100%" class="readonly">
                <tr>
                  <td id="label1"> <?php print CASE_INVESTIGATION_TITLE; ?> </td>
                  <td id="value1">
                    <?php print ucfirst( $case_info[$case_id]['investigation_title'] ); ?>
                    &nbsp;
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print REPORT_CASE_OWNER; ?> </td>
                  <td id="value1">
                    <?php
			$user = get_userinfo( $case_info[$case_id]['owner_id'] );
			if ( strlen($user['name']) > 20 )  {
				$user['name'] = substr( $user['name'], 0, 20 );
			}
			print $user['name'];
			if ( !empty($user['name']) )  {
				print " (<a href=\"javascript:void(0)\" onclick=\"window.open('" . $REPORTSDB . "?task=showstats&user_id=" . $user['id'] . "','" . $TITLE . " -- " . $user['username'] . "')\">" . $user['username'] . "</a>)\n";
			}
                    ?>
                    &nbsp;
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print REPORT_CASE_STATE; ?> </td>
                  <td id="value1">
                    <?php print ucfirst( $case_info[$case_id]['case_open'] ); ?>
                    &nbsp;
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print CASE_TYPE; ?> </td>
                  <td id="value1">
                    <?php print ucfirst( $case_info[$case_id]['investigation_type'] ); ?>
                    &nbsp;
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print REPORT_CASE_DATE_TIME; ?> </td>
                  <td id="value1">
                    <?php
			if ( $case_info[$case_id]['date'] != '0000-00-00' )  {
				print $case_info[$case_id]['date'];
				if ( !empty($case_info[$case_id]['time']) )  {
					print ", " . $case_info[$case_id]['time'];
				}
			}
                    ?>
                    &nbsp;
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print CASE_EXPIRATION; ?> </td>
                  <td id="value1" nowrap="nowrap">
                    <?php
			if ( $case_info[$case_id]['expiration_date'] != '0000-00-00' )  {
				print $case_info[$case_id]['expiration_date'];
			}
                    ?>
                    &nbsp;
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print CASE_LOCATION_TYPE; ?> </td>
                  <td id="value1">
                    <?php print ucfirst( $case_info[$case_id]['loc_type'] ); ?>
                    &nbsp;
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print CASE_CITY; ?> </td>
                  <td id="value1">
                    <?php print ucfirst( $case_info[$case_id]['city'] ); ?>
                    &nbsp;
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print CASE_STATE; ?> </td>
                  <td id="value1">
                    <?php print strtoupper( $case_info[$case_id]['state'] ); ?>
                    &nbsp;
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print REPORT_CASE_RECAP_DATE_TIME; ?> </td>
                  <td id="value1">
                    <?php
			if ( $case_info[$case_id]['recap_date'] != '0000-00-00' )  {
				print $case_info[$case_id]['recap_date'];
				if ( !empty($case_info[$case_id]['recap_time']) )  {
					print ", " . $case_info[$case_id]['recap_time'];
				}
			}
                    ?>
                    &nbsp;
                  </td>
                </tr>
                <tr>
                  <td id="label1"> <?php print CASE_RECAP_LOCATION; ?> </td>
                  <td id="value1">
                    <?php print $case_info[$case_id]['recap_location']; ?>
                    &nbsp;
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
        <!-- Report and Case Information -->


        <div class="divider"> </div>


        <!-- Equipment and geomag/xray/moon Information -->
        <div id="reportheader">
          <div class="row">
            <span class="left"> <strong><?php print REPORT_HEADER_EQUIP; ?></strong> </span>
            <span class="right"> <a href="#" id="equip_fields-toggle">Show/Hide</a> </span>
          </div>
        </div>
        <div id="equip_fields" style="display:block">
        <table cellspacing="0" cellpadding="0" align="center" class="form_table_main">
          <tr>
            <td valign="top" width="64%">

              <!-- Equipment -->
              <table align="center" width="100%">
                <tr>
                  <td>

                    <div class="tabber">

                      <!-- Tech Equipment -->
                      <div class="tabbertab" title="<?php print REPORT_EQUIP_TECH; ?>" id="equipment">
                        <h3> <?php print REPORT_EQUIP_TECH; ?> </h3>
                        <div class="prop"> </div>

                        <?php
				global $TECH_EQUIPMENT;
				print_equip_form( $TECH_EQUIPMENT, 3 );
                        ?>

                        <p>
                        <table cellpadding="0" cellspacing="0" width="90%" align="center">
                          <tr>
                            <td>
                              Other Equipment: <a href="javascript:addTechinput('add_tech_equip', 'tech_equip_div_');" id="add_tech_equip" class="small">more...</a>

                              <?php
				$misc_fields = explode( "|", $TECH_EQUIPMENT['tech_equip_misc']['value'] );
				print_equip_misc_fields( 'tech_equip', $misc_fields );
                              ?>

                            </td>
                          </tr>
                        </table>

                        <div class="clear"></div>
                      </div>
                      <!-- Tech Equipment -->


                      <!-- Audio Equipment -->
                      <div class="tabbertab" title="<?php print REPORT_EQUIP_AUDIO; ?>" id="equipment">
                        <h3> <?php print REPORT_EQUIP_AUDIO; ?> </h3>
                        <div class="prop"> </div>

                        <?php
				global $AUDIO_EQUIPMENT;
				print_equip_form( $AUDIO_EQUIPMENT, 2 );
                        ?>

                        <p>
                        <table cellpadding="0" cellspacing="0" width="90%" align="center">
                          <tr>
                            <td>
                              Other Equipment: <a href="javascript:addAudioinput('add_audio_equip', 'audio_equip_div_');" id="add_audio_equip" class="small">more...</a>

                              <?php
				$misc_fields = explode( "|", $AUDIO_EQUIPMENT['audio_equip_misc']['value'] );
				print_equip_misc_fields( 'audio_equip', $misc_fields );
                              ?>

                            </td>
                          </tr>
                        </table>

                        <div class="clear"></div>
                      </div>
                      <!-- Audio Equipment -->


                      <!-- Video Equipment -->
                      <div class="tabbertab" title="<?php print REPORT_EQUIP_VIDEO; ?>" id="equipment">
                        <h3> <?php print REPORT_EQUIP_VIDEO; ?> </h3>
                        <div class="prop"> </div>

                        <?php
				global $VIDEO_EQUIPMENT;
				print_equip_form( $VIDEO_EQUIPMENT, 2 );
                        ?>

                        <p>
                        <table cellpadding="0" cellspacing="0" width="90%" align="center">
                          <tr>
                            <td>
                              Other Equipment: <a href="javascript:addVideoinput('add_video_equip', 'video_equip_div_');" id="add_video_equip" class="small">more...</a>

                              <?php
				$misc_fields = explode( "|", $VIDEO_EQUIPMENT['video_equip_misc']['value'] );
				print_equip_misc_fields( 'video_equip', $misc_fields );
                              ?>

                            </td>
                          </tr>
                        </table>

                        <div class="clear"></div>
                      </div>
                      <!-- Video Equipment -->


                      <!-- Photo Equipment -->
                      <div class="tabbertab" title="<?php print REPORT_EQUIP_PHOTO; ?>" id="equipment">
                        <h3> <?php print REPORT_EQUIP_PHOTO; ?> </h3>
                        <div class="prop"> </div>

                        <?php
				global $PHOTO_EQUIPMENT;
				print_equip_form( $PHOTO_EQUIPMENT, 2 );
                        ?>

                        <p>
                        <table cellpadding="0" cellspacing="0" width="90%" align="center">
                          <tr>
                            <td>
                              Other Equipment: <a href="javascript:addPhotoinput('add_photo_equip', 'photo_equip_div_');" id="add_photo_equip" class="small">more...</a>

                              <?php
				$misc_fields = explode( "|", $PHOTO_EQUIPMENT['photo_equip_misc']['value'] );
				print_equip_misc_fields( 'photo_equip', $misc_fields );
                              ?>

                            </td>
                          </tr>
                        </table>

                        <div class="clear"></div>
                      </div>
                      <!-- Photo Equipment -->


                      <!-- PSI Equipment -->
                      <div class="tabbertab" title="<?php print REPORT_EQUIP_PSI; ?>" id="equipment">
                        <h3> <?php print REPORT_EQUIP_PSI; ?> </h3>
                        <div class="prop"> </div>

                        <?php
				global $PSI_EQUIPMENT;
				print_equip_form( $PSI_EQUIPMENT, 1 );
                        ?>

                        <p>
                        <table cellpadding="0" cellspacing="0" width="90%" align="center">
                          <tr>
                            <td>
                              Other Equipment: <a href="javascript:addPsiinput('add_psi_equip', 'psi_equip_div_');" id="add_psi_equip" class="small">more...</a>

                              <?php
				$misc_fields = explode( "|", $PSI_EQUIPMENT['psi_equip_misc']['value'] );
				print_equip_misc_fields( 'psi_equip', $misc_fields );
                              ?>

                            </td>
                          </tr>
                        </table>

                        <div class="clear"></div>
                      </div>
                      <!-- PSI Equipment -->

                    </div>
                  </td>
                </tr>
              </table>
              <!-- Equipment -->


            </td>
            <td valign="top">


              <!-- Geomag/Xray/Moon Information -->
              <table align="center" width="100%">
                <tr>
                  <td>

                    <!-- Geomagnetic, X-ray and Moon Phase Tabs -->
                    <div class="tabber">

                      <!-- GEOMAGNETIC -->
                      <?php
			global $ENABLE_GEO_XRAY;
			if ( $ENABLE_GEO_XRAY == 1 )  {
                      ?>
                      <div class="tabbertab" title="<?php print REPORT_GEOMAGNETIC; ?>">
                        <h3> <?php print REPORT_GEOMAGNETIC; ?> </h3>
                        <div class="prop" id="geo"> </div>
                        <?php
				$kp = explode( ':', $REPORTS_VALID_FIELDS['geomag_kp']['value'] );
				if ( empty($kp) || count($kp) == 1 )  {
					$kp = array( "&nbsp;","&nbsp;","&nbsp;","&nbsp;","&nbsp;","&nbsp;","&nbsp;","&nbsp;" );
				}
                        ?>
                        <input type="hidden" name="geomag_kp" value="<?php print $REPORTS_VALID_FIELDS['geomag_kp']['value']; ?>" />
                        <table cellpadding="0" cellspacing="0" class="geomag">
                          <tr>
                            <td align="center" colspan="8">
                              <strong> <?php print GEOMAG_KP; ?> </strong>
                            </td>
                          </tr>
                          <tr>
                            <td id="kp-elem"> 0-3 </td>
                            <td id="kp-elem"> 3-6 </td>
                            <td id="kp-elem"> 6-9 </td>
                            <td id="kp-elem"> 9-12 </td>
                            <td id="kp-elem"> 12-15 </td>
                            <td id="kp-elem"> 15-18 </td>
                            <td id="kp-elem"> 18-21 </td>
                            <td id="kp-elem"> 21-24 </td>
                          </tr>
                          <tr>
                            <?php
				$i = 0;
				foreach ( array_keys($kp) as $key )  {
                            ?>
                            <td id="value" align="center">
                              <input type="text" name="geomag_kp_<?php print $i; ?>" id="geomag_kp_xx" value="<?php print $kp[$key]; ?>" maxlength="<?php print $REPORTS_VALID_FIELDS['geomag_kp']['maxlength']; ?>" READONLY />
                            </td>
                            <?php
					$i++;
				}
                            ?>
                          </tr>
                        </table>

                        <p>
                        <table width="75%" align="center" style="padding-top:5px;" class="geomag">
                          <tr>
                            <td>
                              <strong><?php print GEOMAG_AP; ?></strong>:
                            </td>
                            <td width="70%" id="value">
                              <input type="text" name="geomag_ap" id="geomag_ap" value="<?php print $REPORTS_VALID_FIELDS['geomag_ap']['value']; ?>" maxlength="<?php print $REPORTS_VALID_FIELDS['geomag_ap']['maxlength']; ?>" READONLY />
                            </td>
                          </tr>
                          <tr>
                            <td>
                              <strong><?php print GEOMAG_SUMMARY; ?></strong>:
                            </td>
                            <td width="70%" id="value">
                              <input type="text" name="geomag_summary" id="geomag_summary" value="<?php print $REPORTS_VALID_FIELDS['geomag_summary']['value']; ?>" maxlength="<?php print $REPORTS_VALID_FIELDS['geomag_summary']['maxlength']; ?>" READONLY />
                            </td>
                          </tr>
                        </table>
                        <div style="padding:2px;"></div>
                        <div align="center" id="list_plot_geo">
                          <input type="hidden" name="geomag_list" value="<?php print $REPORTS_VALID_FIELDS['geomag_list']['value']; ?>" />
                          <input type="hidden" name="geomag_plot" value="<?php print $REPORTS_VALID_FIELDS['geomag_plot']['value']; ?>" />
                          <a href="<?php print $REPORTS_VALID_FIELDS['geomag_list']['value']; ?>" target="_blank" id="geomag_list"><?php print GEOMAG_LIST; ?></a> |
                          <a href="<?php print $REPORTS_VALID_FIELDS['geomag_plot']['value']; ?>" target="_blank" id="geomag_list"><?php print GEOMAG_PLOT; ?></a>
                        </div>

                        <div class="clear"></div>
                      </div>
                      <?php
			}  // ENABLE_GEO_XRAY
                      ?>
                      <!-- GEOMAGNETIC -->


                      <!-- XRAY -->
                      <?php
			if ( $ENABLE_GEO_XRAY == 1 )  {
                      ?>
                      <div class="tabbertab" title="<?php print REPORT_XRAY; ?>">
                        <h3> <?php print REPORT_XRAY; ?> </h3>
                        <div class="prop" id="xray"> </div>

                        <table cellpadding="0" cellspacing="2" align="center" class="xray">
                          <tr>
                            <td width="25%">
                              <strong><?php print XRAY_LONG; ?>:</strong>
                            </td>
                            <td id="value">
                              <input type="text" name="xray_long" id="xray_long" value="<?php print $REPORTS_VALID_FIELDS['xray_long']['value']; ?>" maxlength="<?php print $REPORTS_VALID_FIELDS['xray_long']['maxlength']; ?>" READONLY />
                            </td>
                          </tr>
                          <tr>
                            <td width="25%">
                              <strong><?php print XRAY_SHORT; ?>:</strong>
                            </td>
                            <td id="value">
                              <input type="text" name="xray_short" id="xray_short" value="<?php print $REPORTS_VALID_FIELDS['xray_short']['value']; ?>" maxlength="<?php print $REPORTS_VALID_FIELDS['xray_short']['maxlength']; ?>" READONLY />
                            </td>
                          </tr>
                          <tr>
                            <td width="25%">
                              <strong><?php print XRAY_HIGH; ?>:</strong>
                            </td>
                            <td id="value">
                              <input type="text" name="xray_high" id="xray_high" value="<?php print $REPORTS_VALID_FIELDS['xray_high']['value']; ?>" maxlength="<?php print $REPORTS_VALID_FIELDS['xray_high']['maxlength']; ?>" READONLY />
                            </td>
                          </tr>
                          <tr>
                            <td width="25%">
                              <strong><?php print XRAY_LOW; ?>:</strong>
                            </td>
                            <td id="value">
                              <input type="text" name="xray_low" id="xray_low" value="<?php print $REPORTS_VALID_FIELDS['xray_low']['value']; ?>" maxlength="<?php print $REPORTS_VALID_FIELDS['xray_low']['maxlength']; ?>" READONLY />
                            </td>
                          </tr>
                          <tr>
                            <td width="25%">
                              <strong><?php print XRAY_PEAK; ?>:</strong>
                            </td>
                            <td id="value">
                              <input type="text" name="xray_peak" id="xray_peak" value="<?php print $REPORTS_VALID_FIELDS['xray_peak']['value']; ?>" maxlength="<?php print $REPORTS_VALID_FIELDS['xray_peak']['maxlength']; ?>" READONLY />
                            </td>
                          </tr>
                          <tr>
                            <td width="25%">
                              <strong><?php print XRAY_SUMMARY; ?>:</strong>
                            </td>
                            <td id="value">
                              <input type="text" name="xray_summary" id="xray_summary" value="<?php print $REPORTS_VALID_FIELDS['xray_summary']['value']; ?>" maxlength="<?php print $REPORTS_VALID_FIELDS['xray_summary']['maxlength']; ?>" READONLY />
                            </td>
                          </tr>
                        </table>
                        <div style="padding:2px;"></div>
                        <div align="center" id="list_plot_xray">
                          <input type="hidden" name="xray_list" value="<?php print $REPORTS_VALID_FIELDS['xray_list']['value']; ?>" />
                          <input type="hidden" name="xray_plot" value="<?php print $REPORTS_VALID_FIELDS['xray_plot']['value']; ?>" />
                          <a href="<?php print $REPORTS_VALID_FIELDS['xray_list']['value']; ?>" target="_blank" id="xray_list"><?php print XRAY_LIST; ?></a> |
                          <a href="<?php print $REPORTS_VALID_FIELDS['xray_plot']['value']; ?>" target="_blank" id="xray_list"><?php print XRAY_PLOT; ?></a>
                        </div>

                        <div class="clear"></div>
                      </div>
                      <?php
			}  // ENABLE_GEO_XRAY
                      ?>
                      <!-- XRAY -->


                      <!-- Moon Phase -->
                      <?php
			global $ENABLE_MOONPHASE;
			if ( $ENABLE_MOONPHASE == 1 )  {
                      ?>
                      <div class="tabbertab" title="<?php print REPORT_MOON; ?>">
                        <h3> <?php print REPORT_MOON; ?> </h3>
                        <div class="prop" id="moon"> </div>

                        <input type="hidden" name="moon_image" id="moon_image" value="<?php print $REPORTS_VALID_FIELDS['moon_image']['value']; ?>" READONLY />
                        <input type="hidden" name="moon_illum" id="moon_illum" value="<?php print $REPORTS_VALID_FIELDS['moon_illum']['value']; ?>" READONLY />
                        <input type="hidden" name="moon_phase" id="moon_phase" value="<?php print $REPORTS_VALID_FIELDS['moon_phase']['value']; ?>" READONLY />

                        <table cellpadding="0" cellspacing="0" align="center" class="moon_phase">
                          <tr>
                            <td valign="middle" align="center">

                              <br />
                              <div id="moon_phase_image" style="padding:5px;">
                                <?php
					if ( !empty($REPORTS_VALID_FIELDS['moon_image']['value']) )  {
						print "<img src=\"" . $REPORTS_VALID_FIELDS['moon_image']['value'] . "\">\n";
					}
					else  {
						print "<div style=\"height:48px;\"> </div>\n";
					}
                                ?>
                              </div>
                            </td>
                          </tr>
                          <tr>
                            <td>
                              <strong> <?php print MOON_PHASE; ?> </strong> <br />
                              <div id="moon_phase_data">
                              <?php print $REPORTS_VALID_FIELDS['moon_illum']['value'] . " " . $REPORTS_VALID_FIELDS['moon_phase']['value']; ?>
                              <?php
				if ( empty($REPORTS_VALID_FIELDS['moon_illum']['value']) && empty($REPORTS_VALID_FIELDS['moon_phase']['value']) )  {
					print "<div class=\"small\"> No Info </div>\n";
				}
                              ?>
                            </td>
                          </tr>
                        </table>

                        <div class="clear"></div>
                      </div>
                      <?php
			}  // $ENABLE_MOONPHASE
                      ?>
                      <!-- Moon Phase -->

                    </div>
                    <!-- Geomagnetic, X-ray and Moon Phase Tabs -->

                    <div class="small" style="text-align:right;">
                      <a href="javascript:clear_geoxray();" style="text-decoration:none;">Clear Data</a>
                    </div>
                  </td>
                </tr>
              </table>
              <!-- Geomag/Xray/Moon Information -->

            </td>
          </tr>
        </table>
        </div>
        <!-- Equipment and geomag/xray/moon Information -->


        <div class="divider"> </div>


        <!-- Impression Information -->
        <div id="reportheader">
          <div class="row">
            <span class="left"> <strong><?php print REPORT_HEADER_IMPRESSIONS; ?></strong></span>
            <span class="right"> <a href="#" id="impressions_fields-toggle">Show/Hide</a> </span>
          </div>
        </div>
        <div id="impressions_fields" style="display:block;">
        <table cellspacing="0" cellpadding="0" align="center" class="form_table_main">
          <tr>
            <td colspan="2">

              <div class="tabber">

                <div class="tabbertab" title="<?php print REPORT_OUTSIDE_IMPRESSION; ?>">
                  <h3> <?php print REPORT_OUTSIDE_IMPRESSION; ?> </h3>
                  <?php print REPORT_OUTSIDE_IMPRESSION; ?>: <abbr title="<?php print HELP_OUTSIDE_IMPRESSION; ?>"><img src="images/help.gif"></abbr> <br />
                  <textarea name="outside_impr" id="outside_impr" rows="6" cols="50" style="width:100%;"><?php print $REPORTS_IMPRESSIONS_VALID_FIELDS['outside_impr']['value']; ?></textarea>
                  <div style="text-align:right;padding-right:10px;">
                    <a href="JavaScript:taller('outside_impr')" class="medium"><?php print TEXTAREA_TALLER; ?></a> |
                    <a href="JavaScript:shorter('outside_impr')" class="medium"><?php print TEXTAREA_SHORTER; ?></a>
                  </div>
                </div>

                <div class="tabbertab" title="<?php print REPORT_WALKIN_IMPRESSION; ?>">
                  <h3> <?php print REPORT_WALKIN_IMPRESSION; ?> </h3>
                  <?php print REPORT_WALKIN_IMPRESSION; ?>: <abbr title="<?php print HELP_WALKIN_IMPRESSION; ?>"><img src="images/help.gif"></abbr> <br />
                  <textarea name="walkin_impr" id="walkin_impr" rows="6" cols="50" style="width:100%;"><?php print $REPORTS_IMPRESSIONS_VALID_FIELDS['walkin_impr']['value']; ?></textarea>
                  <div style="text-align:right;padding-right:10px;">
                    <a href="JavaScript:taller('walkin_impr')" class="medium"><?php print TEXTAREA_TALLER; ?></a> |
                    <a href="JavaScript:shorter('walkin_impr')" class="medium"><?php print TEXTAREA_SHORTER; ?></a>
                  </div>
                </div>

                <div class="tabbertab" title="<?php print REPORT_CLOSING_IMPRESSION; ?>">
                  <h3> <?php print REPORT_CLOSING_IMPRESSION; ?> </h3>
                  <?php print REPORT_CLOSING_IMPRESSION; ?>: <abbr title="<?php print HELP_CLOSING_IMPRESSION; ?>"><img src="images/help.gif"></abbr> <br />
                  <textarea name="closing_impr" id="closing_impr" rows="6" cols="50" style="width:100%;"><?php print $REPORTS_IMPRESSIONS_VALID_FIELDS['closing_impr']['value']; ?></textarea>
                  <div style="text-align:right;padding-right:10px;">
                    <a href="JavaScript:taller('closing_impr')" class="medium"><?php print TEXTAREA_TALLER; ?></a> |
                    <a href="JavaScript:shorter('closing_impr')" class="medium"><?php print TEXTAREA_SHORTER; ?></a>
                  </div>
                </div>

              </div>
            </td>
          </tr>
        </table>
        </div>
        <!-- Impression Information -->


        <!-- Set up the tabs early. -->
        <script type="text/javascript">
	// <!--
		tabberAutomatic();
	// -->
        </script>


        <!-- Print Room Data -->
	<?php
		// Locate the lowest unused index for the various anomaly fields.
		// These numbers will be used to set the javascript vars such as
		// tech_anomaly_field[x].
		global $NUM_ANOMALIES;
		$tech_field_num = array();
		$anomaly_field_num = array();
		$evp_field_num = array();
		$video_field_num = array();
		for ( $i=1; $i<$NUM_ROOMS+1; $i++ )  {
			$tech_field_num[$i] = $NUM_ANOMALIES+1;
			$anomaly_field_num[$i] = $NUM_ANOMALIES+1;
			$evp_field_num[$i] = $NUM_ANOMALIES+1;
			$video_field_num[$i] = $NUM_ANOMALIES+1;
			for ( $j=1; $j<$NUM_ANOMALIES+1; $j++ )  {
				if ( empty(${'ROOM_DATA_'.$i}['tech_anomaly_data_'.$j]['value']) && $tech_field_num[$i] == $NUM_ANOMALIES+1 )  {
					$tech_field_num[$i] = $j;
					break;
				}
			}
			for ( $j=1; $j<$NUM_ANOMALIES+1; $j++ )  {
				if ( empty(${'ROOM_DATA_'.$i}['anomaly_anomaly_data_'.$j]['value']) && $anomaly_field_num[$i] == $NUM_ANOMALIES+1 )  {
					$anomaly_field_num[$i] = $j;
					break;
				}
			}
			for ( $j=1; $j<$NUM_ANOMALIES+1; $j++ )  {
				if ( empty(${'ROOM_DATA_'.$i}['evp_anomaly_data_'.$j]['value']) && $evp_field_num[$i] == $NUM_ANOMALIES+1 )  {
					$evp_field_num[$i] = $j;
					break;
				}
			}
			for ( $j=1; $j<$NUM_ANOMALIES+1; $j++ )  {
				if ( empty(${'ROOM_DATA_'.$i}['video_anomaly_data_'.$j]['value']) && $video_field_num[$i] == $NUM_ANOMALIES+1 )  {
					$video_field_num[$i] = $j;
					break;
				}
			}
		}
	?>

	<script type="text/javascript">
	// <!--
		// Global vars to keep track of tech_anomaly fields.
		var tech_anomaly_field = new Array();
		var anomaly_anomaly_field = new Array();
		var evp_anomaly_field = new Array();
		var video_anomaly_field = new Array();
		<?php
			for ($i=1; $i<$NUM_ROOMS+1; $i++)  {
				print 'tech_anomaly_field[' . $i . '] = ' . $tech_field_num[$i] . ";\n";
				print 'anomaly_anomaly_field[' . $i . '] = ' . $anomaly_field_num[$i] . ";\n";
				print 'evp_anomaly_field[' . $i . '] = ' . $evp_field_num[$i] . ";\n";
				print 'video_anomaly_field[' . $i . '] = ' . $video_field_num[$i] . ";\n";
			}
		?>
	// -->
	</script>

        <?php
	if ( isset($_REQUEST['available_rooms']) && !empty($_REQUEST['available_rooms']) )  {
		if ( is_numeric($_REQUEST['available_rooms']) && $_REQUEST['available_rooms'] > 0 )  {
			$available_rooms = $_REQUEST['available_rooms'];
		}
		else  {
			$available_rooms = 10;
		}
	}
	elseif ( $num_full > 10 )  {
		$available_rooms = $num_full-1;
	}
	else  {
		$available_rooms = 10;
	}
	if ( isset($_REQUEST['add_num_rooms']) && !empty($_REQUEST['add_num_rooms']) )  {
		if ( is_numeric($_REQUEST['add_num_rooms']) && $_REQUEST['add_num_rooms'] > 0 )  {
			$available_rooms += $_REQUEST['add_num_rooms'];
		}
		if ( $available_rooms > $NUM_ROOMS )  {
			$available_rooms = $NUM_ROOMS;
		}
	}

	for ( $i=1; $i<$NUM_ROOMS+1; $i++ )  {
		if ( $i > $available_rooms )  {
			// Stop when we've reached our maximum number of rooms.
			break;
		}

		$style = 'display:none;';
		if ( $i == 1 )  {
			$style = 'display:block;';
		}
		elseif ( !room_isempty( $i ) )  {
			$style = 'display:block;';
		}

		if ( $i == 8 || $i == 20 )  {
			print "<!-- Set up the tabs early. -->\n";
			print "<script type=\"text/javascript\">\n";
			print "	// <!--\n";
			print "	tabberAutomatic();\n";
			print "	// -->\n";
			print "</script>\n";
		}
        ?>

        <!-- Room <?php print $i; ?> -->
        <div id="room_div_<?php print $i; ?>" style="<?php print $style; ?>">
        <div class="divider"> </div>
        <div id="reportheader">
          <div class="row">
            <span class="left"> 
              <?php
		if ( !empty(${'ROOM_DATA_'.$i}['room_id']['value']) )  {
			print "<strong> " . ${'ROOM_DATA_'.$i}['room_id']['value'] . " </strong>";
		}
		else  {
			print "<strong> " . REPORT_HEADER_ROOM . $i . " </strong>";
                }
              ?>
            </span>
            <span class="right"> <a href="#" id="room_fields_<?php print $i; ?>-toggle">Show/Hide</a> </span>
          </div>
        </div>
        <div id="room_fields_<?php print $i; ?>" style="display:block;">
        <table cellspacing="4" cellpadding="0" align="center" class="form_table_main">
          <tr>
            <td class="form_table">
              <?php print REPORT_ROOM_ID; ?> <abbr title="<?php print HELP_ROOM_ID; ?>"><img src="images/help.gif"></abbr> <br />
              <input type="text" id="room_id_<?php print $i; ?>" name="ROOM_DATA_<?php print $i; ?>[room_id]" value="<?php print ${'ROOM_DATA_'.$i}['room_id']['value']; ?>" size="40" maxlength="<?php print ${'ROOM_DATA_'.$i}['room_id']['maxlength']; ?>" />
            </td>
          </tr>
          <tr>
            <td>


              <!-- Advanced Reporting Fields -->
              <div style="padding-top:5px"> </div>
              <div id="roomitemheader">
                <div class="row">
                  <span class="left"> <strong> Advanced Reporting Options </strong> </span>
                  <span class="right"> <a href="#" id="advanced_reporting_fields_<?php print $i; ?>-toggle">Open/Close</a> </span>
                </div>
              </div>
              <div id="advanced_reporting_fields_<?php print $i; ?>" style="display:none;border:1px solid #999999;">

              <div class="tabber">


                <!-- Technical Measurements -->
                <div class="tabbertab" title="<?php print REPORT_EQUIP_TECH; ?>" id="equipment">
                  <h3> <?php print REPORT_EQUIP_TECH; ?> </h3>
                  <div class="prop"> </div>
                  <table cellpadding="0" cellspacing="0" style="width:100% !important;width:98%;">
                    <tr>
                      <td valign="top" width="35%">

                        <strong> Baseline Measurements </strong>
                        <table cellpadding="0" cellspacing="4" width="100%">
                          <tr>
                            <td id="label1" style="padding-right:10px;"> <?php print REPORT_AC_EMF_MAGNETIC; ?> </td>
                            <td id="value1">
                              <input type="text" name="ROOM_DATA_<?php print $i; ?>[ac_emf_magnetic]" value="<?php print ${'ROOM_DATA_'.$i}['ac_emf_magnetic']['value']; ?>" size="4" maxlength="<?php print ${'ROOM_DATA_'.$i}['ac_emf_magnetic']['maxlength']; ?>" />
                              <select name="ROOM_DATA_<?php print $i; ?>[ac_emf_magnetic_units]" size="1">

                                <?php
					if ( ${'ROOM_DATA_'.$i}['ac_emf_magnetic_units']['value'] == "emf_mg" ||
					     empty(${'ROOM_DATA_'.$i}['ac_emf_magnetic_units']['value']) )  {
                                ?>
                                <option value="emf_mg">mG
                                <option value="emf_kvm">kV/m
                                <?php  } else {  ?>
                                <option value="emf_kvm">kV/m
                                <option value="emf_mg">mG
                                <?php  }  ?>

                              </select>
                            </td>
                          </tr>
                          <tr>
                            <td id="label1"> <?php print REPORT_AC_EMF_ELECTRIC; ?> </td>
                            <td id="value1">
                              <input type="text" name="ROOM_DATA_<?php print $i; ?>[ac_emf_electric]" value="<?php print ${'ROOM_DATA_'.$i}['ac_emf_electric']['value']; ?>" size="4" maxlength="<?php print ${'ROOM_DATA_'.$i}['ac_emf_electric']['maxlength']; ?>" />
                              <select name="ROOM_DATA_<?php print $i; ?>[ac_emf_electric_units]" size="1">

                                <?php
					if ( ${'ROOM_DATA_'.$i}['ac_emf_electric_units']['value'] == "emf_kvm" ||
					     empty(${'ROOM_DATA_'.$i}['ac_emf_electric_units']['value']) )  {
                                ?>
                                <option value="emf_kvm">kV/m
                                <option value="emf_mg">mG
                                <option value="emf_mt">&micro;T
                                <?php
					}
					elseif ( ${'ROOM_DATA_'.$i}['ac_emf_electric_units']['value'] == "emf_mg" )  {
				?>
                                <option value="emf_mg">mG
                                <option value="emf_kvm">kV/m
                                <option value="emf_mt">&micro;T
                                <?php  } else {  ?>
                                <option value="emf_mt">&micro;T
                                <option value="emf_mg">mG
                                <option value="emf_kvm">kV/m
                                <?php } ?>

                              </select>
                            </td>
                          </tr>
                          <tr>
                            <td id="label1"> <?php print REPORT_DC_EMF_MAGNETIC; ?> </td>
                            <td id="value1">
                              <input type="text" name="ROOM_DATA_<?php print $i; ?>[dc_emf_magnetic]" value="<?php print ${'ROOM_DATA_'.$i}['dc_emf_magnetic']['value']; ?>" size="4" maxlength="<?php print ${'ROOM_DATA_'.$i}['dc_emf_magnetic']['maxlength']; ?>" />
                              <select name="ROOM_DATA_<?php print $i; ?>[dc_emf_magnetic_units]" size="1">

                                <?php
					if ( ${'ROOM_DATA_'.$i}['dc_emf_magnetic_units']['value'] == "emf_mt" ||
					     empty(${'ROOM_DATA_'.$i}['dc_emf_magnetic_units']['value']) )  {
                                ?>
                                <option value="emf_mt">&micro;T
                                <option value="emf_vm">V/m
                                <?php  } else {  ?>
                                <option value="emf_vm">V/m
                                <option value="emf_mt">&micro;T
                                <?php  }  ?>

                              </select>
                            </td>
                          </tr>
                          <tr>
                            <td id="label1"> <?php print REPORT_DC_EMF_ELECTRIC; ?> </td>
                            <td id="value1">
                              <input type="text" name="ROOM_DATA_<?php print $i; ?>[dc_emf_electric]" value="<?php print ${'ROOM_DATA_'.$i}['dc_emf_electric']['value']; ?>" size="4" maxlength="<?php print ${'ROOM_DATA_'.$i}['dc_emf_electric']['maxlength']; ?>" />
                              <select name="ROOM_DATA_<?php print $i; ?>[dc_emf_electric_units]" size="1">

                                <?php
					if ( ${'ROOM_DATA_'.$i}['dc_emf_electric_units']['value'] == "emf_mt" ||
					     empty(${'ROOM_DATA_'.$i}['dc_emf_electric_units']['value']) )  {
                                ?>
                                <option value="emf_mt">&micro;T
                                <option value="emf_vm">V/m
                                <?php  } else {  ?>
                                <option value="emf_vm">V/m
                                <option value="emf_mt">&micro;T
                                <?php  }  ?>

                              </select>
                            </td>
                          </tr>
                          <tr>
                            <td id="label1"> <?php print REPORT_DC_EMF_SUM; ?> </td>
                            <td id="value1">
                              <input type="text" name="ROOM_DATA_<?php print $i; ?>[dc_emf_sum]" value="<?php print ${'ROOM_DATA_'.$i}['dc_emf_sum']['value']; ?>" size="4" maxlength="<?php print ${'ROOM_DATA_'.$i}['dc_emf_sum']['maxlength']; ?>" />
                              <select name="ROOM_DATA_<?php print $i; ?>[dc_emf_sum_units]" size="1">

                                <?php
					if ( ${'ROOM_DATA_'.$i}['dc_emf_sum_units']['value'] == "emf_mt" ||
					     empty(${'ROOM_DATA_'.$i}['dc_emf_sum_units']['value']) )  {
                                ?>
                                <option value="emf_mt">&micro;T
                                <option value="emf_vm">V/m
                                <?php  } else {  ?>
                                <option value="emf_vm">V/m
                                <option value="emf_mt">&micro;T
                                <?php  }  ?>

                              </select>
                            </td>
                          </tr>
                          <tr>
                            <td id="label1"> <?php print REPORT_TEMP; ?> </td>
                            <td id="value1">
                              <input type="text" name="ROOM_DATA_<?php print $i; ?>[temp]" value="<?php print ${'ROOM_DATA_'.$i}['temp']['value']; ?>" size="4" maxlength="<?php print ${'ROOM_DATA_'.$i}['temp']['maxlength']; ?>" />
                              <select name="ROOM_DATA_<?php print $i; ?>[temp_units]" size="1">

                                <?php
					if ( ${'ROOM_DATA_'.$i}['temp_units']['value'] == "temp_f" ||
					     empty(${'ROOM_DATA_'.$i}['temp_units']['value']) )  {
                                ?>
                                <option value="temp_f">F
                                <option value="temp_c">&deg;C
                                <?php  } else {  ?>
                                <option value="temp_c">&deg;C
                                <option value="temp_f">F
                                <?php  }  ?>

                              </select>
                            </td>
                          </tr>
                          <tr>
                            <td id="label1"> <?php print REPORT_RELATIVE_HUMIDITY; ?> </td>
                            <td id="value1">
                              <input type="text" name="ROOM_DATA_<?php print $i; ?>[rel_humidity]" value="<?php print ${'ROOM_DATA_'.$i}['rel_humidity']['value']; ?>" size="4" maxlength="<?php print ${'ROOM_DATA_'.$i}['rel_humidity']['maxlength']; ?>" />
                              <select name="ROOM_DATA_<?php print $i; ?>[rel_humidity_units]" size="1">
                                <option value="rh_percent">%
                              </select>
                            </td>
                          </tr>
                          <tr>
                            <td id="label1"> <?php print REPORT_BAROMETRIC; ?> </td>
                            <td id="value1">
                              <input type="text" name="ROOM_DATA_<?php print $i; ?>[barometric]" value="<?php print ${'ROOM_DATA_'.$i}['barometric']['value']; ?>" size="4" maxlength="<?php print ${'ROOM_DATA_'.$i}['barometric']['maxlength']; ?>" />
                              <select name="ROOM_DATA_<?php print $i; ?>[barometric_units]" size="1">
                                <option value="mbar">mbar
                                <option value="inHg">inHg
                                <option value="hPa">hPa
                              </select>
                            </td>
                          </tr>
                        </table>

                      </td>
                      <td valign="top" style="border-left:2px solid #999999;padding-left:10px;">

                        <strong> Anomalous Measurements </strong> <br />

                        <div style="padding:4px 0px 0px 4px;">
                          <table cellpadding="0" cellspacing="2" class="readonly2" width="80%" align="center">
                            <tr>
                              <td id="label1" align="center">
                                <strong> Time </strong>
                              </td>
                              <td id="label1" align="center">
                                <strong> Measurement Type </strong>
                              </td>
                            </tr>
                            <tr>
                              <td id="value1" align="center">
                                <select name="tech_anomaly_time_hour_<?php print $i; ?>" id="tech_anomaly_time_hour_<?php print $i; ?>" size="1">
                                  <?php
					for ($q=0;$q<25;$q++)  {
						if ( $q < 10 )  {
							$q = '0' . $q;
						}
						print "<option value=\"" . $q . "\">" . $q. "\n";
					}
                                  ?>
                                </select>
                                <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                                <select name="tech_anomaly_time_minute_<?php print $i; ?>" id="tech_anomaly_time_minute_<?php print $i; ?>" size="1">
                                  <?php
					for ($q=0;$q<60;$q++)  {
						if ( $q < 10 )  {
							$q = '0' . $q;
						}
						print "<option value=\"" . $q . "\">" . $q . "\n";
					}
                                  ?>
                                </select>
                                <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                                <select name="tech_anomaly_time_second_<?php print $i; ?>" id="tech_anomaly_time_second_<?php print $i; ?>" size="1">
                                  <?php
					for ($q=0;$q<60;$q++)  {
						if ( $q < 10 )  {
							$q = '0' . $q;
						}
						print "<option value=\"" . $q . "\">" . $q . "\n";
					}
                                  ?>
                                </select>
                              </td>
                              <td id="value1" align="center">
                                <select name="tech_anomaly_type_<?php print $i; ?>" id="tech_anomaly_type_<?php print $i; ?>" size="1">
                                  <option>
                                  <option value="AC EMF (Magnetic)">AC EMF (Magnetic)
                                  <option value="AC EMF (Electric)">AC EMF (Electric)
                                  <option value="DC EMF (Magnetic)">DC EMF (Magnetic)
                                  <option value="DC EMF (Electric)">DC EMF (Electric)
                                  <option value="DC EMF (Sum)">DC EMF (Sum)
                                  <option value="Temperature">Temperature
                                  <option value="Relative Humidity">Relative Humidity
                                  <option value="Barometric">Barometric
                                </select>
                              </td>
                            </tr>
                          </table>

                          <table cellpadding="0" cellspacing="2" class="readonly2" width="70%" align="center">
                            <tr>
                              <td id="label1" align="center">
                                <strong> +/- </strong>
                              </td>
                              <td id="label1" align="center">
                                <strong> Value </strong>
                              </td>
                              <td id="label1" align="center">
                                <strong> Units </strong>
                              </td>
                            </tr>
                            <tr>
                              <td id="value1" align="center">
                                <select name="tech_anomaly_plusminus_<?php print $i; ?>" id="tech_anomaly_plusminus_<?php print $i; ?>" size="1">
                                  <option value="+">+
                                  <option value="-">-
                                </select>
                              </td>
                              <td id="value1" align="center">
                                <input type="text" name="tech_anomaly_value_<?php print $i; ?>" id="tech_anomaly_value_<?php print $i; ?>" value="" size="6" maxlength="<?php print $REPORTS_ROOM_DATA_VALID_FIELDS['tech_anomaly_data_1']['maxlength']; ?>" />
                              </td>
                              <td id="value1" align="center">
                                <select name="tech_anomaly_units_<?php print $i; ?>" id="tech_anomaly_units_<?php print $i; ?>" size="1">
                                  <option>
                                  <?php
					foreach ( array_keys($TECH_UNITS) as $key )  {
						print "<option value=\"" . $key . "\">" . $TECH_UNITS[$key] . "\n";
					}
                                  ?>
                                </select>
                              </td>
                            </tr>
                            <tr>
                              <td colspan="3" align="right">
                                <div style="padding-top:2px;"><button type="button" onClick="JavaScript:add_tech_anomaly('<?php print $i; ?>');">Add Anomaly</button></div>
                              </td>
                            </tr>
                          </table>
                        </div>

                        <div style="margin-top:8px;border-top: 3px double #999999;padding:8px 0px 0px 10px;">

                        <?php
				$tech_fields = array ();
				$tech_fields[0] = $tech_fields[1] = $tech_fields[2] = $tech_fields[3] = $tech_fields[4] = '';
				for ( $j=1; $j<10; $j++ )  {
					$style = 'display:none;';
					if ( !empty(${'ROOM_DATA_'.$i}['tech_anomaly_data_'.$j]['value']) )  {
						$style = 'display:block;';

						// The tech anomalies are split up into 5 fields, so we 
						// need to split up the fields from the database source.
						$tech_fields = explode( '|', ${'ROOM_DATA_'.$i}['tech_anomaly_data_'.$j]['value'] );
					}
                        ?>
                        <div id="tech_anomaly_div_<?php print $j.'_'.$i; ?>" style="<?php print $style; ?>">
                          <input type="hidden" name="ROOM_DATA_<?php print $i; ?>[tech_anomaly_data_<?php print $j; ?>]" id="tech_anomaly_data_<?php print $j.'_'.$i; ?>" value="<?php print ${'ROOM_DATA_'.$i}['tech_anomaly_data_'.$j]['value']; ?>" maxlength="<?php print ${'ROOM_DATA_'.$i}['tech_anomaly_data_'.$j]['maxlength']; ?>" />
                          <table cellspacing="0" cellpadding="0" width="90%" align="center">
                            <tr>
                              <td style="width:auto;border:1px solid #999999;white-space:nowrap;">
                                <input type="text" name="tech_anomaly_time_<?php print $j.'_'.$i; ?>" id="tech_anomaly_time_<?php print $j.'_'.$i; ?>" value="<?php print $tech_fields[0]; ?>" maxlength="<?php print ${'ROOM_DATA_'.$i}['tech_anomaly_data_'.$j]['maxlength']; ?>" size="8" class="readonly_input" READONLY />
                                <input type="text" name="tech_anomaly_type_<?php print $j.'_'.$i; ?>" id="tech_anomaly_type_<?php print $j.'_'.$i; ?>" value="<?php print $tech_fields[1]; ?>" maxlength="<?php print ${'ROOM_DATA_'.$i}['tech_anomaly_data_'.$j]['maxlength']; ?>" size="20" class="readonly_input" READONLY />
                                <input type="text" name="tech_anomaly_plusminus_<?php print $j.'_'.$i; ?>" id="tech_anomaly_plusminus_<?php print $j.'_'.$i; ?>" value="<?php print $tech_fields[2]; ?>" maxlength="<?php print ${'ROOM_DATA_'.$i}['tech_anomaly_data_'.$j]['maxlength']; ?>" size="2" class="readonly_input" style="text-align:center;" READONLY />
                                <input type="text" name="tech_anomaly_value_<?php print $j.'_'.$i; ?>" id="tech_anomaly_value_<?php print $j.'_'.$i; ?>" value="<?php print $tech_fields[3]; ?>" maxlength="<?php print ${'ROOM_DATA_'.$i}['tech_anomaly_data_'.$j]['maxlength']; ?>" size="6" class="readonly_input" READONLY />
                                <input type="text" name="tech_anomaly_units_<?php print $j.'_'.$i; ?>" id="tech_anomaly_units_<?php print $j.'_'.$i; ?>" value="<?php print $tech_fields[4]; ?>" maxlength="<?php print ${'ROOM_DATA_'.$i}['tech_anomaly_data_'.$j]['maxlength']; ?>" size="6" class="readonly_input" READONLY />
                              </td>
                              <td style="padding-left:4px;white-space:nowrap;">
                                <a href="JavaScript:delete_tech_anomaly(<?php print $j.','.$i; ?>);" class="small">Delete</a>
                              </td>
                            </tr>
                          </table>
                        </div>
                        <?php  }  ?>

                        </div>
                      </td>
                    </tr>
                  </table>

                  <div class="clear"></div>
                </div>
                <!-- Technical Measurements -->


                <!-- Anomalies -->
                <div class="tabbertab" title="<?php print REPORT_ANOMALIES; ?>" id="equipment">
                  <h3> <?php print REPORT_ANOMALIES; ?> </h3>
                  <div class="prop"> </div>

                  <table cellpadding="0" cellspacing="4" style="width:100% !important;width:98%;">
                    <tr>
                      <td valign="top" style="width:auto;border-right:2px solid #999999;">

                        <strong> Anomaly Type </strong>

                        <table cellpadding="0" cellspacing="4" class="nowrap">
                          <tr>
                            <td id="label1">
                              <div>
                                <div style="float:left;"> Mist/Ecto &nbsp; </div>
                                <div style="float:right;"> <abbr title="<?php print HELP_REPORT_ANOMALY_MIST; ?>"><img src="images/help.gif"></abbr> </div>
                              </div>
                            </td>
                            <td id="value1">
                              <input type="checkbox" name="anomaly_type_<?php print $i; ?>" id="anomaly_type_ecto_<?php print $i; ?>" value="ecto" />
                            </td>
                          </tr>
                          <tr>
                            <td id="label1" valign="top">
                              <div>
                                <div style="float:left;"> Apparition &nbsp; </div>
                                <div style="float:right;"> <abbr title="<?php print HELP_REPORT_ANOMALY_APPARITION; ?>"><img src="images/help.gif"></abbr> </div>
                              </div>
                            </td>
                            <td id="value1">
                              <input type="checkbox" name="anomaly_type_<?php print $i; ?>" id="anomaly_type_apparition_<?php print $i; ?>" onClick="JavaScript:showhide('apparition_types_<?php print $i; ?>');" value="apparition" />
                              <div id="apparition_types_<?php print $i; ?>" style="display:none;padding-left:15px;">
                                <input type="checkbox" name="anomaly_apparition_type_<?php print $i; ?>" id="anomaly_apparition_shadow_<?php print $i; ?>" value="shadow" /> Shadow <br />
                                <input type="checkbox" name="anomaly_apparition_type_<?php print $i; ?>" id="anomaly_apparition_vaporous_<?php print $i; ?>" value="vaporous" /> Vaporous <br />
                                <input type="checkbox" name="anomaly_apparition_type_<?php print $i; ?>" id="anomaly_apparition_partial_<?php print $i; ?>" value="partial" /> Partial <br />
                                <input type="checkbox" name="anomaly_apparition_type_<?php print $i; ?>" id="anomaly_apparition_full_<?php print $i; ?>" value="full" /> Full
                              </div>
                            </td>
                          </tr>
                          <tr>
                            <td id="label1">
                              <div>
                                <div style="float:left;"> Orb &nbsp; </div>
                                <div style="float:right;"> <abbr title="<?php print HELP_REPORT_ANOMALY_ORB; ?>"><img src="images/help.gif"></abbr> </div>
                              </div>
                            </td>
                            <td id="value1">
                              <input type="checkbox" name="anomaly_type_<?php print $i; ?>" id="anomaly_type_orb_<?php print $i; ?>" value="orb" />
                            </td>
                          </tr>
                          <tr>
                            <td id="label1">
                              <div>
                                <div style="float:left;"> Audible Anomaly &nbsp; </div>
                                <div style="float:right;"> <abbr title="<?php print HELP_REPORT_ANOMALY_AUDIBLE; ?>"><img src="images/help.gif"></abbr> </div>
                              </div>
                            </td>
                            <td id="value1">
                              <input type="checkbox" name="anomaly_type_<?php print $i; ?>" id="anomaly_type_audible_<?php print $i; ?>" onClick="JavaScript:showhide('audible_types_<?php print $i; ?>');" value="audible" />
                              <div id="audible_types_<?php print $i; ?>" style="display:none;padding-left:15px;">
                                <input type="checkbox" name="anomaly_audible_type_<?php print $i; ?>" id="anomaly_audible_knock_<?php print $i; ?>" value="knock" /> Knock <br />
                                <input type="checkbox" name="anomaly_audible_type_<?php print $i; ?>" id="anomaly_audible_footsteps_<?php print $i; ?>" value="footsteps" /> Footsteps <br />
                                <input type="checkbox" name="anomaly_audible_type_<?php print $i; ?>" id="anomaly_audible_voice_<?php print $i; ?>" value="voice" /> Voice <br />
                              </div>
                            </td>
                          </tr>
                          <tr>
                            <td id="label1">
                              <div>
                                <div style="float:left;"> Visual Anomaly &nbsp; </div>
                                <div style="float:right;"> <abbr title="<?php print HELP_REPORT_ANOMALY_VISUAL; ?>"><img src="images/help.gif"></abbr> </div>
                              </div>
                            </td>
                            <td id="value1">
                              <input type="checkbox" name="anomaly_type_<?php print $i; ?>" id="anomaly_type_visual_<?php print $i; ?>" onClick="JavaScript:showhide('visual_types_<?php print $i; ?>');" value="visual" />
                              <div id="visual_types_<?php print $i; ?>" style="display:none;padding-left:15px;">
                                <input type="checkbox" name="anomaly_visual_type_<?php print $i; ?>" id="anomaly_visual_knock_<?php print $i; ?>" value="luminous" /> Luminous/Glow <br />
                                <input type="checkbox" name="anomaly_visual_type_<?php print $i; ?>" id="anomaly_visual_other_<?php print $i; ?>" value="other" /> Other Non-Apparition <br />
                              </div>
                           </td>
                          </tr>
                          <tr>
                            <td id="label1">
                              <div>
                                <div style="float:left;"> Physical Anomaly &nbsp; </div>
                                <div style="float:right;"> <abbr title="<?php print HELP_REPORT_ANOMALY_PHYSICAL; ?>"><img src="images/help.gif"></abbr> </div>
                              </div>
                            </td>
                            <td id="value1">
                              <input type="checkbox" name="anomaly_type_<?php print $i; ?>" id="anomaly_type_physical_<?php print $i; ?>" onclick="JavaScript:showhide('physical_anomaly_types_<?php print $i; ?>');"  value="physical" />
                              <div id="physical_anomaly_types_<?php print $i; ?>" style="display:none;padding-left:15px;">
                                <input type="checkbox" name="anomaly_physical_type_<?php print $i; ?>" id="anomaly_physical_touch_<?php print $i; ?>" value="moving_object" /> Moving Object <br />
                                <input type="checkbox" name="anomaly_physical_type_<?php print $i; ?>" id="anomaly_physical_touch_<?php print $i; ?>" value="touch" /> Touch <br />
                                <input type="checkbox" name="anomaly_physical_type_<?php print $i; ?>" id="anomaly_physical_touch_<?php print $i; ?>" value="grab/pull" /> Grab/Pull <br />
                                <input type="checkbox" name="anomaly_physical_type_<?php print $i; ?>" id="anomaly_physical_scratch_<?php print $i; ?>" value="scratch" /> Scratch <br />
                                <input type="checkbox" name="anomaly_physical_type_<?php print $i; ?>" id="anomaly_physical_burn_<?php print $i; ?>" value="burn" /> Burn <br />
                                <input type="checkbox" name="anomaly_physical_type_<?php print $i; ?>" id="anomaly_physical_nausea_<?php print $i; ?>" value="nausea/dizziness" /> Nausea/Dizziness
                              </div>
                            </td>
                          </tr>
                        </table>

                      </td>
                      <td valign="top" style="padding:0px 10px 0px 10px;border-right:2px solid #999999;" width="220">

                        <div>
                          <strong> Time </strong> <br />
                          <select name="anomaly_anomaly_time_hour_<?php print $i; ?>" id="anomaly_anomaly_time_hour_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<24;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                            <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                            <select name="anomaly_anomaly_time_minute_<?php print $i; ?>" id="anomaly_anomaly_time_minute_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<60;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q . "\n";
				}
                            ?>
                            </select>
                            <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                            <select name="anomaly_anomaly_time_second_<?php print $i; ?>" id="anomaly_anomaly_time_second_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<60;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q . "\n";
				}
                            ?>
                          </select>
                        </div>

                        <div style="padding-top:4px;">
                          <strong> Description </strong> <br />
                          <textarea name="anomaly_description_<?php print $i; ?>" id="anomaly_description_<?php print $i; ?>" rows="6" cols="16" style="width:99%;"></textarea>
                        </div>

                        <div style="padding-top:2px;">
                          <button type="button" onClick="JavaScript:add_anomaly_anomaly(<?php print $i; ?>);">Add Anomaly</button>
                        </div>

                      </td>
                      <td valign="top" style="padding:4px 0px 0px 10px;">
                        <strong> Anomalies </strong>

                        <?php
				for ( $j=1; $j<10; $j++ )  {
					$style = 'display:none;';
					if ( !empty(${'ROOM_DATA_'.$i}['anomaly_anomaly_data_'.$j]['value']) )  {
						$style = 'display:block;';
					}
                        ?>
                        <div id="anomaly_anomaly_div_<?php print $j.'_'.$i; ?>" style="<?php print $style; ?>">
                          <table cellspacing="0" cellpadding="0" width="95%">
                            <tr>
                              <td style="width:auto;padding-right:2px;border:1px solid #999999;white-space:nowrap;text-align:center;">
                                <input type="text" name="ROOM_DATA_<?php print $i; ?>[anomaly_anomaly_data_<?php print $j; ?>]" id="anomaly_anomaly_data_<?php print $j.'_'.$i; ?>" value="<?php print ${'ROOM_DATA_'.$i}['anomaly_anomaly_data_'.$j]['value']; ?>" maxlength="<?php print ${'ROOM_DATA_'.$i}['anomaly_anomaly_data_'.$j]['maxlength']; ?>" width="20" style="width:98% !important;width:13em" class="readonly_input" READONLY />
                              </td>
                              <td style="padding-left:4px;white-space:nowrap;">
                                <a href="JavaScript:delete_anomaly_anomaly(<?php print $j.','.$i; ?>);" class="small">Delete</a>
                              </td>
                            </tr>
                          </table>
                        </div>
                        <?php  }  ?>

                        <div style="width:170px;height:1px;margin:0;padding:0"> </div>
                      </td>
                    </tr>
                  </table>

                  <div class="clear"></div>
                </div>
                <!-- Anomalies -->


                <!-- EVP -->
                <div class="tabbertab" title="<?php print REPORT_EVP; ?>" id="equipment">
                  <h3> <?php print REPORT_EVP; ?> </h3>
                  <div class="prop"> </div>

                  <div class="row2">
                    <div class="left" style="width:54%;border-right:2px solid #999999;">
                      <strong> EVP Information </strong>

                      <table cellpadding="0" cellspacing="4" width="100%">
                        <tr>
                          <td id="label1" style="white-space:nowrap;">
                            <abbr title="<?php print HELP_REPORT_ANOMALY_EVP_LABEL; ?>"><img src="images/help.gif"></abbr>
                            Tape/Recording Label:
                          </td>
                          <td id="value1">
                             <input type="text" name="evp_anomaly_label_<?php print $i; ?>" id="evp_anomaly_label_<?php print $i; ?>" value="" size="25" maxlength="100" />
                          </td>
                        </tr>
                        <tr>
                          <td id="label1">
                            <abbr title="<?php print HELP_REPORT_ANOMALY_EVP_TIME; ?>"><img src="images/help.gif"></abbr>
                            <?php print REPORT_TAPE_TIME; ?>
                          </td>
                          <td id="value1" style="font-weight:bold">
                            <select name="evp_anomaly_hour_<?php print $i; ?>" id="evp_anomaly_hour_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<24;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                            <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                            <select name="evp_anomaly_minute_<?php print $i; ?>" id="evp_anomaly_minute_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<60;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                            <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                            <select name="evp_anomaly_second_<?php print $i; ?>" id="evp_anomaly_second_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<60;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                          </td>
                        </tr>
                        <tr>
                          <td id="label1">
                            <abbr title="<?php print HELP_REPORT_ANOMALY_EVP_REALTIME; ?>"><img src="images/help.gif"></abbr>
                            <?php print REPORT_REAL_TIME; ?>
                          </td>
                          <td id="value1" style="font-weight:bold">
                            <select name="evp_anomaly_realhour_<?php print $i; ?>" id="evp_anomaly_realhour_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<24;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                            <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                            <select name="evp_anomaly_realminute_<?php print $i; ?>" id="evp_anomaly_realminute_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<60;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                            <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                            <select name="evp_anomaly_realsecond_<?php print $i; ?>" id="evp_anomaly_realsecond_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<60;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                          </td>
                        </tr>
                        <tr>
                          <td id="label1">
                            <abbr title="<?php print HELP_REPORT_ANOMALY_EVP_DESCR; ?>"><img src="images/help.gif"></abbr>
                            <?php print REPORT_DESCRIPTION; ?>
                          </td>
                          <td id="value1">
                            <textarea name="evp_anomaly_descr_<?php print $i; ?>" id="evp_anomaly_descr_<?php print $i; ?>" rows="5" cols="30" style="width:95%"></textarea>
                          </td>
                        </tr>
                        <tr>
                          <td colspan="2" align="right">
                            <div style="padding-right:10px;">
                              <button type="button" onClick="JavaScript:add_evp_anomaly(<?php print $i; ?>);">Add Anomaly</button>
                            </div>
                          </td>
                        </tr>
                      </table>
                    </div>
                    <div class="right" style="width:44%;margin:0;">
                      <strong> Anomalies </strong>
                      <?php
			for ( $j=1; $j<10; $j++ )  {
				$style = 'display:none;';
				if ( !empty(${'ROOM_DATA_'.$i}['evp_anomaly_data_'.$j]['value']) )  {
					$style = 'display:block;';
				}
                      ?>
                      <div id="evp_anomaly_div_<?php print $j.'_'.$i; ?>" style="<?php print $style; ?>">
                        <table cellspacing="0" cellpadding="2" width="98%" style="margin-left:6px;">
                          <tr>
                            <td style="width:auto;border:1px solid #999999;white-space:nowrap;overflow:hidden;text-align:center">
                              <input type="text" name="ROOM_DATA_<?php print $i; ?>[evp_anomaly_data_<?php print $j; ?>]" id="evp_anomaly_data_<?php print $j.'_'.$i; ?>" value="<?php print ${'ROOM_DATA_'.$i}['evp_anomaly_data_'.$j]['value']; ?>" maxlength="<?php print ${'ROOM_DATA_'.$i}['evp_anomaly_data_'.$j]['maxlength']; ?>" size="20" style="width:98% !important;width:270px;" maxlength="1200" class="readonly_input" READONLY />
                            </td>
                            <td style="padding-left:4px;white-space:nowrap;">
                              <a href="JavaScript:delete_evp_anomaly(<?php print $j.','.$i; ?>);" class="small">Delete</a>
                            </td>
                          </tr>
                        </table>
                      </div>
                      <?php  }  ?>

                    </div>
                  </div>
                  <div class="clear"></div>
                </div>
                <!-- EVP -->


                <!-- Video -->
                <div class="tabbertab" title="<?php print REPORT_VIDEO; ?>" id="equipment">
                  <h3> <?php print REPORT_VIDEO; ?> </h3>
                  <div class="prop"> </div>

                  <div class="row2">
                    <div class="left" style="width:54%;border-right:2px solid #999999;">
                      <strong> Video Information </strong>

                      <table cellpadding="0" cellspacing="4" width="100%">
                        <tr>
                          <td id="label1" style="white-space:nowrap;">
                            <abbr title="<?php print HELP_REPORT_ANOMALY_VIDEO_LABEL; ?>"><img src="images/help.gif"></abbr>
                            Tape/Recording Label:
                          </td>
                          <td id="value1">
                             <input type="text" name="video_anomaly_label_<?php print $i; ?>" id="video_anomaly_label_<?php print $i; ?>" value="" size="25" maxlength="100" />
                          </td>
                        </tr>
                        <tr>
                          <td id="label1">
                            <abbr title="<?php print HELP_REPORT_ANOMALY_VIDEO_TIME; ?>"><img src="images/help.gif"></abbr>
                            <?php print REPORT_TAPE_TIME; ?>
                          </td>
                          <td id="value1" style="font-weight:bold;">
                            <select name="video_anomaly_hour_<?php print $i; ?>" id="video_anomaly_hour_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<24;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                            <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                            <select name="video_anomaly_minute_<?php print $i; ?>" id="video_anomaly_minute_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<60;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                            <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                            <select name="video_anomaly_second_<?php print $i; ?>" id="video_anomaly_second_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<60;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                          </td>
                        </tr>
                        <tr>
                          <td id="label1">
                            <abbr title="<?php print HELP_REPORT_ANOMALY_VIDEO_REALTIME; ?>"><img src="images/help.gif"></abbr>
                            <?php print REPORT_REAL_TIME; ?>
                          </td>
                          <td id="value1" style="font-weight:bold">
                            <select name="video_anomaly_realhour_<?php print $i; ?>" id="video_anomaly_realhour_<?php print $i; ?>" size="1">
                            <?php
				for ( $q=0;$q<24;$q++ )  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                            <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                            <select name="video_anomaly_realminute_<?php print $i; ?>" id="video_anomaly_realminute_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<60;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                            <span style="height:100%;padding: 0 0 3px 0;"><strong>:</strong></span>
                            <select name="video_anomaly_realsecond_<?php print $i; ?>" id="video_anomaly_realsecond_<?php print $i; ?>" size="1">
                            <?php
				for ($q=0;$q<60;$q++)  {
					if ( $q < 10 )  {
						$q = '0' . $q;
					}
					print "<option value=\"" . $q . "\">" . $q. "\n";
				}
                            ?>
                            </select>
                          </td>
                        </tr>
                        <tr>
                          <td id="label1">
                            <abbr title="<?php print HELP_REPORT_ANOMALY_VIDEO_DESCR; ?>"><img src="images/help.gif"></abbr>
                            <?php print REPORT_DESCRIPTION; ?>
                          </td>
                          <td id="value1">
                            <textarea name="video_anomaly_descr_<?php print $i; ?>" id="video_anomaly_descr_<?php print $i; ?>" rows="5" cols="30" style="width:95%"></textarea>
                          </td>
                        </tr>
                        <tr>
                          <td colspan="2" align="right">
                            <div style="padding-right:10px;">
                              <button type="button" onClick="JavaScript:add_video_anomaly(<?php print $i; ?>);">Add Anomaly</button>
                            </div>
                          </td>
                        </tr>
                      </table>
                    </div>
                    <div class="right" style="width:44%;margin:0">
                      <strong> Anomalies </strong>
                      <?php
			for ( $j=1; $j<10; $j++ )  {
				$style = 'display:none;';
				if ( !empty(${'ROOM_DATA_'.$i}['video_anomaly_data_'.$j]['value']) )  {
					$style = 'display:block;';
				}
                      ?>
                      <div id="video_anomaly_div_<?php print $j.'_'.$i; ?>" style="<?php print $style; ?>">
                        <table cellspacing="0" cellpadding="2" width="98%" style="margin-left:6px;">
                          <tr>
                            <td style="width:auto;border:1px solid #999999;white-space:nowrap;overflow:hidde;text-align:center">
                              <input type="text" name="ROOM_DATA_<?php print $i; ?>[video_anomaly_data_<?php print $j; ?>]" id="video_anomaly_data_<?php print $j.'_'.$i; ?>" value="<?php print ${'ROOM_DATA_'.$i}['video_anomaly_data_'.$j]['value']; ?>" maxlength="<?php print ${'ROOM_DATA_'.$i}['video_anomaly_data_'.$j]['maxlength']; ?>" size="20" style="width:98% !important;width:270px;" maxlength="1200" class="readonly_input" READONLY />
                            </td>
                            <td style="padding-left:4px;white-space:nowrap;">
                              <a href="JavaScript:delete_video_anomaly(<?php print $j.','.$i; ?>);" class="small">Delete</a>
                            </td>
                          </tr>
                        </table>
                      </div>
                      <?php  }  ?>

                    </div>
                  </div>
                  <div class="clear"></div>
                </div>
                <!-- Video -->


              </div>
              <!-- End Tabs -->


              </div>
              <!-- Advanced Reporting Fields -->


              <!-- Room Notes Field -->
              <div style="padding-top:10px;"> </div>
              <div id="roomitemheader">
                <div class="row">
                  <span class="left"> <strong> Notes </strong> </span>
                  <span class="right"> <a href="#" id="notes_field_<?php print $i; ?>-toggle">Open/Close</a> </span>
                </div>
              </div>
              <div id="notes_field_<?php print $i; ?>" style="display:block;border:1px solid #999999;">

              <table cellpadding="0" cellspacing="4" width="100%">
                <tr>
                  <td id="label1" valign="top" style="width:70px"> <?php print REPORT_NOTES; ?> </td>
                  <td id="value1">
                    <textarea name="ROOM_DATA_<?php print $i; ?>[notes]" rows="7" cols="50" id="notes_<?php print $i; ?>" style="width:100%;"><?php print ${'ROOM_DATA_'.$i}['notes']['value']; ?></textarea>
                  </td>
                </tr>
              </table>
              <div style="text-align:right;padding-right:10px;">
                <a href="JavaScript:taller('notes_<?php print $i; ?>')" class="medium"><?php print TEXTAREA_TALLER; ?></a> |
                <a href="JavaScript:shorter('notes_<?php print $i; ?>')" class="medium"><?php print TEXTAREA_SHORTER; ?></a>
              </div>

              </div>
              <!-- Room Notes Field -->


            </td>
          </tr>
        </table>
        </div>
        </div>
        <!-- Room <?php print $i; ?> -->

        <?php
          }  // End printing room data.
        ?>

        <div>
          <a href="javascript:addRoominput('add_room', 'room_div_');" id="add_room" style="font-size:larger;">Add Room</a>
        </div>

        <?php
		print "<script type=\"text/javascript\">\n";
		print "	// <!--\n";
		print "	tabberAutomatic();\n";
		print "	// -->\n";
		print "</script>\n";

//		if ( !empty($show_rooms) )  {
//			print "<script type=\"text/javascript\">\n";
//			print "// <!--\n";
//			foreach ( $show_rooms as $key )  {
//				print "document.getElementById('room_div_' + ".$key.").style.display='block';\n";
//			}
//			print "// -->\n";
//			print "</script>\n";
//		}
        ?>

        <p>
        <table cellspacing="0" cellpadding="0" align="center" class="form_table_main" style="padding:4px;">
          <tr>
            <td align="center" valign="middle">
              <span style="padding-left:110px !important;padding-left:120px"> <button type="submit">Save Report</button> </span>
            </td>
            <td align="right" nowrap valign="middle" class="normal" style="width:120px;padding-right:6px">
              <input type="hidden" name="available_rooms" value="<?php print $available_rooms; ?>" />
              <strong> Add Rooms: </strong> <input type="text" name="add_num_rooms" size="2" maxlength="2" value="" />
            </td>
          </tr>
        </table>

        <div id="reportheader" title="Files Associated with this case:">
            <strong>Files Associated with this case:</strong>
	</div>
	<?php
            // open this directory
            $myDirectory = opendir("./uploads");

            // get each entry
            while($entryName = readdir($myDirectory)) {
            $dirArray[] = $entryName;
            }

            // close directory
            closedir($myDirectory);

            //	count elements in array
            $indexCount	= count($dirArray);

            // sort 'em
            sort($dirArray);

            // print 'em
            print("<TABLE cellspacing=\"0\" cellpadding=\"0\" class=\"form_table_main\">\n");
            print("<TR><TH align=\"left\"><strong>Filename</strong></TH><th align=\"left\"><strong>Filetype</strong></th><th align=\"left\"><strong>Filesize</strong></th></TR>\n");
            // loop through the array of files and print them all
            if (count($dirArray) == 2 ) {
                print ("<tr><td>No files associated with this case.</td></tr>"); }
		else {
                    for($index=0; $index < $indexCount; $index++) {
                    if (substr("$dirArray[$index]", 0, 1) != "." || substr("$dirArray[$index]", 0, 5) != $REPORTS_VALID_FIELDS['case_id']['value']) { // don't list hidden files
                    if (substr("$dirArray[$index]", 0, 5) == $REPORTS_VALID_FIELDS['case_id']['value']) { //don't list non-case files
                    print("<TR><TD><a href=\"uploads/".$dirArray[$index]."\">$dirArray[$index]</a></td>");
                    print("<td>");
                    print(filetype("uploads/".$dirArray[$index]));
                    print("</td>");
                    print("<td>");
                    print(filesize("uploads/".$dirArray[$index]));
                    print("</td>");
                    print("</TR>\n");
		}
		}
		}
		}
		print("</TABLE>\n");
	?>
	</div>

        </form>
        <!-- Report Form -->


<!--Begin upload form section to implement file uploads related to the case.
    Work in progess, be warned, this might steal your cat and drink all of
    your coffee if you actually use this. -- Corey Reichle 22 July 2009 -->

        <div>
        <a href="upload.php?case_id=<?php echo $REPORTS_VALID_FIELDS['case_id']['value'] ?>&owner_id=<?php echo $user['name'] ?>" target="_uploadform" style="font-size:larger;">Click here to add a file to this report</a>
        </div>

      </div>
      <!-- Center Column -->

    </td>
  </tr>
</table>